### ISSUE TITLE
Feature tracker

### ISSUE THREAD

**Issue by nikpcenicni** [nikpcenicni/panda-swap-app#1]
[ In Progress ] Refactor Existing Code Base 
 - [x] Separate summary into independent components (Print Summary, and file list)
 - [x] Merge File List and Fileupload into one section on bottom of page (Allow for file uploading by dragging file anywhere on the page)
 - [x] Simplify and merge helper functions into simple files instead of nesting in components
 - [x] Add settings button and popup to change gcode-preview settings and show/hide details in print summary and file details
 - [x] Add custom gcode between merges, and option to customize/replace code
 - [x] save all settings in browser cache or better way of caching so they retain after refreshes
 - [x] Dynamic text to be used for translations
 - [x] compact summary mode
 - [x] readme & documentation
 - [x] show and hide preview based on setting
 - [ ] add placeholder gcode
 - [ ] fix show printer info
